import "./globals.css";
import { workSans } from "./utils/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${workSans.className} antialiased outline-none focus:ring-0`}
      >
        {children}
      </body>
    </html>
  );
}
